### ISSUE TITLE
我在用plateformio编译时，出现如下报错。能否帮忙解答。

### ISSUE THREAD

**Issue by zhzysyx** [leonlucc/arduino-tencent-cloud-iot-sdk#1]
c:/.platformio/packages/toolchain-xtensa-esp32@8.4.0+2021r2-patch5/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: .pio\build\esp32dev\lib1f2\libTencentCloudIoTSDK.a(TencentCloudIoTSDK.cpp.o):(.literal._ZN18TencentCloudIoTSDK5beginER6ClientPKcS3_S3_m+0x4c): undefined reference to `base64::decodeLength(char const*)'
c:/.platformio/packages/toolchain-xtensa-esp32@8.4.0+2021r2-patch5/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: .pio\build\esp32dev\lib1f2\libTencentCloudIoTSDK.a(TencentCloudIoTSDK.cpp.o):(.literal._ZN18TencentCloudIoTSDK5beginER6ClientPKcS3_S3_m+0x50): undefined reference to `base64::decode(char const*, unsigned char*)'
c:/.platformio/packages/toolchain-xtensa-esp32@8.4.0+2021r2-patch5/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: .pio\build\esp32dev\lib1f2\libTencentCloudIoTSDK.a(TencentCloudIoTSDK.cpp.o): in function `TencentCloudIoTSDK::begin(Client&, char const*, char const*, char const*, unsigned long)':
C:\Users\֪\xba\xf5\xd5\xdfҲ\Documents\PlatformIO\Projects\esp32/.pio/libdeps/esp32dev/TencentCloudIoTSDK/src/TencentCloudIoTSDK.cpp:260: undefined refeerence to `base64::decodeLength(char const*)'
c:/.platformio/packages/toolchain-xtensa-esp32@8.4.0+2021r2-patch5/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\֪\xba\xf5\xd5\xdfҲ\Documents\PlatformIO\Projects\esp32/.pio/libdeps/esp32dev/TencentCloudIoTSDK/src/TencentCloudIoTSDK.cpp:261: undefined referencee to `base64::decode(char const*, unsigned char*)'
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\esp32dev\firmware.elf] Error 1
============================================================= [FAILED] Took 15.98 seconds =============================================================

**Comment by zhzysyx** [comment]
我把提供的示例粘贴到main.cpp里编译后，就出现了这样的报错。

**Comment by zdlavggwykr99** [comment]
接入腾讯云时，日志报错。
Device connect,version:4,keepalive:60,cleansession:1,clientip:39.144.156.28 | FAIL, hmac sign error

MQTT连接失败，返回码为5，意思是连接未经授权。

我应该正确填写了三元组信息，所以才能在设备日志里看到连接失败的消息？
请问应该如何解决？
